### ISSUE TITLE
I need this altered code with out passphrase

### ISSUE THREAD

**Issue by bsde1234** [robinmoisson/staticrypt#118] opened 2019-11-03 09:51 UTC
In one of my site I need to hide the real code from visitors, I think this can be done with this script. But I dont need passphrase for this. I need to hide the links of my videos. How to achieve this? In this script the real source code is hiding, right?

**Comment by aliglelo** [comment] 2019-11-04 03:11
leave passphrase empty ,when page will be loaded you just need to click login without typing anything...
Simple

**Comment by bsde1234** [comment] 2019-11-04 09:46
@aliglelo Thanks for the tip. I already tried it. But in professional site I need a better approach.

**Comment by aliglelo** [comment] 2019-11-05 02:49
have you checked html obfuscation technique?

**Comment by robinmoisson** [comment] 2022-04-23 10:37
Hi, all you can do with this tool is password protect your file - it will [look like this](https://robinmoisson.github.io/staticrypt/example_encrypted.html). All of your source code is encrypted and will be decrypted by the user when they enter the passphrase.

The issue is lacking information to really understand what going on so I'm closing it, feel free to reopen with more details if that's still relevant to you.

**Closed by robinmoisson** 2022-04-23 10:37 UTC

**Comment by oleteacher** [comment] 2022-11-17 12:24
A way to use staticrypt and embed the passphrase so user does not have to enter it into a form. Maybe as a string into the URL?
