### ISSUE TITLE
Can't run from file URL

### ISSUE THREAD

**Issue by stephanwehner** [robinmoisson/staticrypt#16] opened 2017-06-16 16:52 UTC
When I open the URL file:///path/to/repo/index.html in my Chrome or Firefox browser, and fill out the form, the Download-HTML-File button does not get enabled, even after adding a config to disable-cross-domain-policy.

How to work with this from a file URL?

**Comment by jackwilsdon** [comment] 2017-06-16 17:42
You'll need to [allow file access from files](https://stackoverflow.com/a/18587027/2664985) as well to load the `crypto-js.js` file.

**Comment by robinmoisson** [comment] 2017-06-17 18:22
@stephanwehner What's your use case, do you want to use the website completely offline or is it for something else? Can you use crypto-js from a CDN?

I ran into the same issue so I pointed a local server on my repo copy but I understand it's not very user friendly. The problem is the password-prompt template that's loaded in ajax, one easy fix would be to embed it in `index.html` - as a javascript string for example.

But you'd still need to connect to the internet to get a copy of crypto-js. Is that interesting to you?

**Comment by robinmoisson** [comment] 2018-01-08 10:29
If you want to use the tool locally I'd recommend to use the new CLI - I'm closing this issue, let me know if your case differs.

**Closed by robinmoisson** 2018-01-08 10:29 UTC
