### ISSUE TITLE
Bug key.clamp not a function

### ISSUE THREAD

**Issue by adminy** [robinmoisson/staticrypt#149] opened 2022-11-29 20:27 UTC
The error is:
```javascript
/home/adminy/project_test/node_modules/crypto-js/hmac.js:58
                    key.clamp();
                        ^

TypeError: key.clamp is not a function
    at Object.init (/home/adminy/project_test/node_modules/crypto-js/hmac.js:58:18)
    at subtype.init (/home/adminy/project_test/node_modules/crypto-js/core.js:86:46)
    at Object.create (/home/adminy/project_test/node_modules/crypto-js/core.js:113:32)
    at Object.compute (/home/adminy/project_test/node_modules/crypto-js/pbkdf2.js:75:30)
    at C.PBKDF2 (/home/adminy/project_test/node_modules/crypto-js/pbkdf2.js:138:36)
    at Object.hashPassphrase (/home/adminy/project_test/node_modules/staticrypt/lib/cryptoEngine/cryptojsEngine.js:50:35)
    at encode (/home/adminy/project_test/node_modules/staticrypt/lib/codec.js:19:43)
    at Object.<anonymous> (/home/adminy/project_test/node_modules/staticrypt/cli/index.js:170:26)
    at Module._compile (node:internal/modules/cjs/loader:1119:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
```

I literally just installed the library and then tried to run it on a blank compiled solidjs project:
```sh
npx degit solidjs/templates/js project_test
cd project_test
npm i https://github.com/robinmoisson/staticrypt
npm run build
npx staticrypt dist/index.html
```

Running this on node version `v18.9.0` and on a macos Ventura `13.0.1`.

**Comment by robinmoisson** [comment] 2022-11-29 22:49
Hey @adminy, thanks for the details. I tried the same steps on the same node version and can't reproduce.

Looking it up, it looks like that error might be related to the input password, though I'm unsure how. Do you have any particularly special character in it? If you test with the password `test`, does it still fail in the same way? Can there be an encoding other than UTF-8 that's at play?

**Comment by adminy** [comment] 2022-11-30 01:11
Ok so test based password works no problem, but as soon as I try a number based one it throws up this error.

**Comment by robinmoisson** [comment] 2022-11-30 08:08
Good catch, thank you! This is now fixed and the npm package has been updated.

**Closed** 2022-11-30 08:07 UTC
